bg_color: '#272822'
bottom_spacing: '1'
font_color: '#fff'
font_family: monospace
font_size: 14
insertion_blink: false
insertion_color: '#d5c4a1'
menu_active_bg: '#38342b'
menu_active_fg: '#d5c4a1'
menu_bg: '#181816'
padding_x: '5'
padding_y: '5'
tab_size: 4
text_wrap: none
top_spacing: '1'

# MAKE SURE TO SAVE AFTER EVERY CHANGE.
# THIS WARNING EXISTS BECAUSE RESIZING THE WINDOW WITH CTRL SCROLL WHEEL RELOADS THE FILE.